export const profile = {
  name: 'Kazım Etiksan',
  initials: 'ke',
  title: 'Yazılım · Yapay zekâ · Eğitim',
  intro: 'Fikirleri yazılıma, bilgiyi değere dönüştürüyorum. Mobil uygulamalar, yapay zekâ çözümleri ve kurumsal eğitim.',
  about: 'Teknolojiyi, insanların ve kurumların gerçek ihtiyaçlarıyla buluşturuyorum.',
  bio: 'Mobil uygulama geliştirme, teknik danışmanlık, kurumsal eğitim ve ekip yönetimi alanlarında çalışıyorum. 2013 yılında kurduğum Piksel Mutfak bünyesinde farklı sektörlerdeki kurumlara çözümler üretiyorum. Son dönem çalışmalarım AI Agent ve Chatbox geliştirme, yapay zekâ danışmanlığı ve eğitim üzerine yoğunlaşıyor.',
  email: 'kazim@pikselmutfak.com',
  phone: '+90 532 487 12 00',
  linkedin: '',
  cvUrl: '/Kazim_Etiksan_CV.pdf',
  skills: ['Yapay zekâ çözümleri', 'Mobil uygulama geliştirme', 'Kurumsal eğitim', 'Teknik danışmanlık', 'Ekip yönetimi'],
  experience: [
    { period: '2013 — Günümüz', title: 'Kurucu', organization: 'Piksel Mutfak Bilişim Hizmetleri', description: 'Mobil uygulama ve yapay zekâ çözümleri, kurumsal eğitim, danışmanlık ve dış kaynak personel sağlama hizmetleri. Mobil geliştirme ekibi yönetimi.' },
    { period: '2009 — 2013', title: 'Mobil Uygulama Geliştirici', organization: 'Serbest Çalışan', description: 'Novartis, Bayer, Turkcell, Mövenpick ve TRT için mobil uygulama geliştirme.' },
    { period: '2004 — 2009', title: 'Teknik Danışman', organization: 'Netron Bilişim Akademisi', description: '' },
    { period: '2003 — 2004', title: 'Teknik Danışman', organization: 'Bilge Adam Bilgi Teknolojileri Akademisi', description: '' },
  ],
  education: [
    { period: '1998 — 2002', title: 'İşletme · Lisans', organization: 'İstanbul Üniversitesi, İktisat Fakültesi', description: '' },
    { period: '2003', title: 'Mesleki Eğitimler', organization: 'Bilge Adam Bilgi Teknolojileri Akademisi', description: 'MCSE, MCSA ve MCDBA eğitimleri.' },
  ],
  projects: [
    { title: 'Yapay Zekâ Çözümleri', period: '2024 — 2026', description: 'AI Agent ve Chatbox geliştirme; yapay zekâ danışmanlığı ve eğitim hizmetleri.', tags: ['Yapay zekâ', 'Danışmanlık', 'Eğitim'] },
    { title: 'Anadolu Sigorta', period: '2019 — 2023', description: 'ReactJS eğitimleri ve mevcut web portallarının React’a geçiş sürecinin yönetimi.', tags: ['React', 'Kurumsal eğitim'] },
    { title: 'Polisan', period: '2019 — 2020', description: 'Sadakat amaçlı mobil uygulama geliştirme. Uygulamanın yönetimi günümüze kadar devam ediyor.', tags: ['Mobil uygulama'] },
    { title: 'Arçelik, Migros ve BNP Sigorta', period: '2017 — 2019', description: 'Dış kaynak personel sağlama ve danışmanlık hizmetleri.', tags: ['Danışmanlık', 'Ekip'] },
    { title: 'Koç Grubu', period: '2017 — 2019', description: 'Arçelik, TürkTraktör, Yapı Kredi ve Zer için Azure bulut yönetimi eğitimleri.', tags: ['Azure', 'Kurumsal eğitim'] },
    { title: 'Borusan Manheim', period: '2016 — 2017', description: 'İkinci el araç satışına yönelik pazaryeri uygulaması geliştirme.', tags: ['Pazaryeri', 'Uygulama geliştirme'] },
    { title: 'Kuveyt Türk', period: '2014’te başlayan çalışma', description: 'Yazılım ekibine iOS uygulama geliştirme eğitimi ve bir yıl boyunca mobil geliştirme ekibi yönetimi.', tags: ['iOS', 'Eğitim', 'Ekip yönetimi'] },
    { title: 'Doğuş Yayın Grubu', period: '2014', description: 'Kral TV ve Kral Radyo uygulamalarının geliştirilmesi.', tags: ['Mobil uygulama', 'Medya'] },
    { title: 'Hürriyet', period: '2013', description: 'Hürriyet gazetesi için eGazete tablet uygulamasının geliştirilmesi.', tags: ['Tablet uygulaması', 'Medya'] },
  ],
};
